### ISSUE TITLE
Pre-populate image in Harbor registry

### ISSUE THREAD

**Issue by surajyadav-git** [dsohk/workshops#2]
Pre-populate image Rancher hello-world (or anything which is more suitable e.g. nginx) to Harbor registry

**Comment by dsohk** [comment]
@surajyadav-git Would you please specify which image to be pre-populated?

**Comment by surajyadav-git** [comment]
Harbor Registry:
Image: rancher/hello-world
ACR:
Anything which you have already build earlier

**Comment by dsohk** [comment]
amended the terraform script to upload the required image to harbor registry in cd266d0803f6817a0e52e61c859e586b0f35551f
