### ISSUE TITLE
Kubectl shell isn't accessible from Rancher downstream cluster UI

### ISSUE THREAD

**Issue by surajyadav-git** [dsohk/workshops#3]
Kubectl shell isn't accessible from Rancher downstream cluster UI. However, it's working fine from the Rancher Management Server

**Comment by dsohk** [comment]
It seems I am unable to reproduce this problem. It works for me. Would you please reprovision your lab and try again?

<img width="620" alt="image" src="https://user-images.githubusercontent.com/37406127/179673176-60cba041-04b0-491b-ae1f-b63f716ceb9f.png">

**Comment by surajyadav-git** [comment]
Agree. Not replicable anymore.
