### ISSUE TITLE
Scenario Azure - Rancher+NeuVector 

### ISSUE THREAD

**Issue by dipakcpatel78** [dsohk/workshops#5]
Using the automation with scenario Azure with Rancher +NeuVector, I had to install NeuVector manually via the Cluster tool. The trick is we have to select Under Container Runtime - K3s Container Runtime for RKE2 cluster. 
Can we automate the deployment of NeuVector so that people can link on NeuVector link to open NeuVector directly.
Suraj & I both had to figure out how to get NeuVector running.

**Comment by dsohk** [comment]
This request has been implemented with the `terraform-modules/neuvector` where the helm chart values are configured for RKE2.
